* archlinux 利用 org babel 生成配置文件

完全需要配置的配置文件直接生成文件
增量修改配置的配置文件，像hyprland.config 不生成，只记录配置项，然后复制修改
字体等二进制文件，复制到对应目录

** 免密操作

免输密码

#+begin_src sh
  sudo nvim /etc/sudoers.d/00_neo
  neo ALL=(ALL) NOPASSWD: ALL
#+end_src

免登录

https://wiki.archlinux.org/title/Getty

#+begin_src sh
  sudo nvim /etc/systemd/system/getty@tty1.service.d/autologin.conf
  # content
  [Service]
  ExecStart=
  ExecStart=-/usr/bin/agetty --noreset --noclear --autologin neo - ${TERM}
#+end_src

** 生成本地ssh密钥
#+begin_src bash
  ssh-keygen -t rsa -C "ganymede0915@gmail.com"
  # git clone 切换成 ssh
  # To change an existing repository from HTTPS to SSH, you use the git remote set-url command.
  git remote set-url origin git@github.com:shun-sfoo/.emacs.d.git
  git remote -v
#+end_src

** npm 全局安装应用配置

使用用户级 npm 全局目录
#+begin_src bash
  mkdir -p ~/.local/npm
  npm config set prefix ~/.local/npm
  # add to .bashrc
  export PATH="$HOME/.local/npm/bin:$PATH"
  npm install -g typescript-language-server typescript @biomejs/biome
#+end_src

** 使用uv作为python工具流
1. emacs的basedpyright会识别.venv中的包，所以无需在配置emacs
2. compile 命令中通过 uv run 执行python， 也无需管理emacs配置
3. uv下载包的命令， uv add 会自动创建.venv 下载也会下载到虚拟环境中
4. uv 运行代码时也会先激活虚拟环境，所以在emacs中使用不需要做任何适配，除了 run-python这种情况。

   使用 rassumfrassum 配置多lsp服务器
  uv tool install rassumfrassum
  uv tool install basedpyright
  uv tool install ruff

  新建一个项目
  uv init new_project
  uv python install 3.12
  cd new_project
  uv python pin 3.12
  uv add package
  uv run main.py


** 备份到移动硬盘的命令

#+begin_src bash
  sudo rsync -ah --no-o --no-g --info=progress2 source_dir/ target_dir/
#+end_src

1. -a (归档模式)：
核心功能：递归复制目录，并保留所有属性（权限、时间戳、软链接、属主等）。
对硬盘友好：因为它保留了时间戳，下次运行时，rsync 能准确判断哪些文件没变过，从而跳过它们，避免对硬盘进行无谓的重复写入。

--no-o：明确告诉 rsync 不要尝试更改文件所有者。
--no-g：明确告诉 rsync 不要尝试更改文件所属组。

2. -h (人类可读)：
将文件大小显示为 K/M/G 单位，方便阅读进度。

3. --info=progress2 (关键参数)：
展示进度：这是比旧版 -P 或 --progress 更先进的参数。它会在同一行动态更新当前正在传输的文件进度（例如：file.mp4  50.00%  10MB/s），而不是为每个文件打印一堆新行刷屏。这让界面非常清爽，你能清楚看到整体速度和当前文件状态。

路径末尾的 /：
重要：/源文件夹路径/ 后面的斜杠表示“复制该文件夹里面的内容”。如果不加斜杠，会把“源文件夹”本身也拷贝到目标位置，导致层级多了一层（例如：/dest/源文件夹/...）。


** haskell 工具
haskell 工具会用到两个 pandoc 和 shellcheck 如果直接用arch仓库的包，会带来海量的依赖，

因此跟 uv 和 rustup 一样 安装 ghcup 使用 cabal 源码编译安装

使用 https://mirrors.ustc.edu.cn/ghcup/ 的源，安装ghcup, 注意中间附加的组件都选否

全部安装完之后再利用 ghcup tui 去下载

#+begin_src bash
  curl --proto '=https' --tlsv1.2 -sSf https://mirrors.ustc.edu.cn/ghcup/sh/bootstrap-haskell | BOOTSTRAP_HASKELL_YAML=https://mirrors.ustc.edu.cn/ghcup/ghcup-metadata/ghcup-latest.yaml sh
#+end_src

 这一步会自动配置好cabal的源，因此只需要配置
~/.ghcup/config.yaml
#+begin_src config
  url-source:
  OwnSource:
    - https://mirrors.ustc.edu.cn/ghcup/ghcup-metadata/ghcup-latest.yaml
#+end_src

最后通过 cabal install pandoc ShellCheck

注意 ShellCheck的大小写 下载就可以使用了

** 配置文件
*** zshrc

#+begin_src bash :tangle ~/.zshrc
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000   # the number of items for the internal history list
export SAVEHIST=1000000   # maximum number of items for the history file
# The meaning of these options can be found in man page of `zshoptions`.
setopt HIST_IGNORE_ALL_DUPS  # do not put duplicated command into history list
setopt HIST_SAVE_NO_DUPS  # do not save duplicated command
setopt HIST_REDUCE_BLANKS  # remove unnecessary blanks
setopt INC_APPEND_HISTORY_TIME  # append command to history file immediately after execution
setopt EXTENDED_HISTORY  # record command start time

[ -d /usr/share/zsh/plugins ] \
  && source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh \
  && source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

## rust tools
[ -e /usr/bin/starship ] && eval "$(starship init zsh)"
[ -e /usr/bin/zoxide ] && eval "$(zoxide init zsh)"
[ -e /usr/bin/mcfly ] && eval "$(mcfly init zsh)"

alias ls="eza --icons=auto"

check_network() {
    if curl -s --connect-timeout 3 --max-time 5 https://www.baidu.com &>/dev/null; then
        echo "网络正常"
        return 0
    else
        echo "WiFi已连接但无网络"
        return 1
    fi
}

pacadd() {
    check_network || { echo "网络不可用"; return 1; }
    if [ $# -lt 1 ]; then
        echo "need package name"
        return 1
    fi

    sudo pacman -S --needed "$@"
    pacman -Qqe >"$HOME/Transformer/packages.list"
}

pacrm() {
    check_network || { echo "网络不可用"; return 1; }
    if [ $# -lt 1 ]; then
        echo "need package name"
        return 1
    fi

    sudo pacman -Rns "$@"
    pacman -Qqe >"$HOME/Transformer/packages.list"
}

pacup() {
    check_network || { echo "网络不可用"; return 1; }
    sudo pacman -Syyu
}

#+end_src

*** zprofile

#+begin_src bash :tangle ~/.zprofile
[ "$(tty)" = "/dev/tty1" ] && exec start-hyprland
#+end_src

*** fontconfig

#+begin_src xml :tangle ~/.config/fontconfig :mkdirp yes
<?xml version="1.0"?>
  <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
  <fontconfig>
    <alias>
      <family>sans-serif</family>
      <prefer>
        <family>Noto Sans CJK SC</family>
        <family>Symbols Nerd Font</family>
        <family>Noto Color Emoji</family>
        <family>Noto Sans CJK TC</family>
        <family>Noto Sans CJK JP</family>
      </prefer>
    </alias>
    <alias>
      <family>serif</family>
      <prefer>
        <family>Noto Sans CJK SC</family>
        <family>Symbols Nerd Font</family>
        <family>Noto Color Emoji</family>
        <family>Noto Sans CJK TC</family>
        <family>Noto Sans CJK JP</family>
      </prefer>
    </alias>
    <alias>
      <family>monospace</family>
      <prefer>
        <family>Noto Sans Mono CJK SC</family>
        <family>Symbols Nerd Font</family>
        <family>Noto Color Emoji</family>
        <family>Noto Sans Mono CJK TC</family>
        <family>Noto Sans Mono CJK JP</family>
      </prefer>
    </alias>
  </fontconfig>
#+end_src

*** ghostty

#+begin_src config :tangle ~/.config/ghostty/config.ghostty :mkdirp yes
theme = TokyoNight Storm
font-family = "Operator Mono Lig Book"
font-size = 13
alpha-blending = "native"
background-opacity = 0.8
background-blur = true
copy-on-select = clipboard
#+end_src

*** hyprland

#+begin_src lua
  local menu = "tofi-drun --drun-launch=true --font $HOME/.local/share/fonts/Operator_Mono_with_Lig/OperatorMonoSSmLig-Book.otf"
  
  hl.config({
  xwayland = {
    force_zero_scaling = true
  }
  
  hl.env("GDK_SCALE", "2")

  hl.on("hyprland.start", function () 
    hl.exec_cmd("waybar")
  end)
  
})
#+end_src

*** tofi

#+begin_src config  :tangle ~/.config/tofi/config :mkdirp yes
width = 100%
height = 100%
border-width = 0
outline-width = 0
padding-left = 35%
padding-top = 35%
result-spacing = 25
num-results = 5
font = monospace
background-color = #000A
#+end_src

*** waybar

**** config.jsonc

#+begin_src json :tangle ~/.config/waybar/config.jsonc :mkdirp yes
// -*- mode: jsonc -*-
{
  "height": 30,
  "spacing": 4,
  "modules-left": [
    "hyprland/workspaces"
  ],
  "modules-center": [
    "hyprland/window"
  ],
  "modules-right": [
    "cpu",
    "battery",
    "backlight",
    "memory",
    "wireplumber",
    "temperature",
    "network",
    "clock",
    "tray",
    "custom/updates"
  ],
  "hyprland/workspaces": {
    "format": "{icon}",
    "on-scroll-up": "hyprctl dispatch workspace e+1",
    "on-scroll-down": "hyprctl dispatch workspace e-1"
  },
  "hyprland/window": {
    "format": "{}",
    "rewrite": {
      "(.*) — Firefox Developer Edition": "  $1",
      "vim": " ",
      "make": " "
    },
    "separate-outputs": true
  },
  "network": {
    "format-icons": [
      "󰤯",
      "󰤟",
      "󰤢",
      "󰤥",
      "󰤨"
    ],
    "format": "{icon}",
    "format-wifi": " ⇣{bandwidthDownBytes}  ⇡{bandwidthUpBytes} {icon} ",
    "format-ethernet": "⇣ {bandwidthDownBytes:7}  ⇡ {bandwidthUpBytes:7}  󰈀 ",
    "format-disconnected": "󰤮",
    "tooltip-format-wifi": "{essid} ({frequency} GHz)",
    "tooltip-format-disconnected": "Disconnected",
    "interval": 2
  },
  "wireplumber": {
    "format": "{volume}% {icon}",
    "format-icons": [
      " ",
      " ",
      "  "
    ]
  },
  "temperature": {
    "hwmon-path": "/sys/class/hwmon/hwmon6/temp1_input",
    "format": "{temperatureC}°C "
  },
  "clock": {
    "format": "{:%H:%M}   ",
    "tooltip-format": "<big>{:%Y %B} </big>\n<tt><small>{calendar}</small></tt> ",
    "format-alt": "{:%Y-%m-%d}  "
  },
  "cpu": {
    "format": "{usage}% 󰻠 "
  },
  "memory": {
    "format": "{percentage}%  "
  },
  "custom/weather": {
    "format": "{}",
    "exec": "~/.config/waybar/scripts/weather.sh",
    "interval": 3600,
    "signal": 8, // 定义信号编号，用于手动触发更新
    "return-type": "json",
    "on-click": "xdg-open 'https://v2.wttr.in/Wuhan'"
  },
  "custom/updates": {
    "format": "{}  ",
    "exec": "~/.config/waybar/scripts/check-updates.sh",
    "return-type": "json",
    "signal": 7, // 定义信号编号，用于手动触发更新
    "interval": 900,
    "on-click": "pkill -RTMIN+7 waybar" // 点击时向waybar发送8号信号
  }
}
#+end_src


**** style.css

#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  @import "/etc/xdg/waybar/style.css";

  window#waybar {
      background-color: rgba(36, 40, 59, 0.5);
      border-bottom: 3px solid rgba(100, 114, 125, 0.5);
      color: #c0caf5;
      transition-property: background-color;
      transition-duration: .5s;
  }

  #workspaces button.active {
      background-color: #545c7e;
      box-shadow: inset 0 -3px #c0caf5;
  }

  #custom-weather {
      background-color: #73daca;
      color: #000000;
      padding-left: 10px;  /* 左侧间隙 */
      padding-right: 10px; /* 右侧间隙 */
  }

  #network {
      background-color: #7aa2f7;
      min-width: 160px; 
  }

  #cpu {
      background-color: #9fe044;
  }

  #memory {
      background-color: #bb9af7
  }


  #wireplumber {
      background-color: #c0caf5
  }

  #clock {
      background-color: #414868
  }

  #tray {
      background-color: #f7768e
  }

  #temperature {
      background-color: #e0af68
  }

  #custom-updates {
      background-color: #73daca;
      color: #000000;
      padding-left: 10px;  /* 左侧间隙 */
      padding-right: 10px; /* 右侧间隙 */
  }

  #custom-updates.update-available {
      background-color: #f7768e;
  }
#+end_src


**** srcipts

***** checkupdate

#+begin_src bash :tangle ~/.config/waybar/scripts/check-updates.sh :mkdirp yes
#!/usr/bin/env sh

updates=$(checkupdates 2>/dev/null)

if [ -z "$updates" ]; then
  num=0
else
  num=$(echo "$updates" | wc -l)
fi

# Bash的参数扩展（如${parameter:-word}）主要进行的是文本替换。
# 当parameter未设置或为空时，它直接将word部分作为字符串整体替换上去，不会主动解析word中的转义序列（如\n、\t等）
# 这些转义序列会保持其字面形式。
jq -c -n \
  --arg text "$num" \
  --arg tooltip "${updates:-系统已是最新状态}" \
  '{
    text: $text,
    tooltip: $tooltip,
    class: (if $text != "0" then "update-available" else "" end)
  }'

#+end_src

***** weather 

#+begin_src bash :tangle ~/.config/waybar/scripts/weather.sh :mkdirp yes
#!/usr/bin/env sh
weather=$(curl -s "https://wttr.in/武汉?format=3")
cat <<EOF
{"text": "${weather}", "tooltip": "点击显示完整预报"}
EOF
#+end_src
