* Mastering Emacs Notebook

** The Theory of Movement

*** The Basics

查看有哪些 repeat map 通过 `M-x describe-repeat-maps`

`C-\` :Undo

`C-x u` 实现了 repeat-mode 可以通过 `C-x u... u` 的方式来连续撤销

In Emacs, Every action you take is recorded in the undo ring,
and this includes the action of undoing something. Emacs will
group certain commands together into one coheesive undo cell
like typing characters or repeating the same command many times
in a row. Some events will always "seal" the undo record and
start a new one. Pressing RET, backspace, or moving the point
around are three such examples.

在 emacs中， 你所执行的每一个操作都会记录在撤销环中。
这设置包括执行撤销操作本身。Emacs会将某些命令组合成一个连贯的撤销单元，
例如连续输入多个字符或多次重复执行相同的命令。有些操作会“封闭”当前的
撤销记录并开始一个新的记录。按下回车键，退格或移动光标就是三个这样的例子。

Repeated undo commands will undo more and more things but if you break
the cycle -- for instance by moving around or editing text -- Emacs will
not resume from where you left off. Instead, the items you just undid were
added to the undo ring as redo records. That means when you undo again, you
will actually undo (redo) the actions you just did until you get to the state
you were at when you last stopped -- then Emacs will undo the rest of the
changes in you buffer.

重复执行撤销（undo） 命令会撤销越来越多的操作， 但如果你中断了这个循环--例如通过
光标或编辑文本--Emacs将不会从你中断的继续撤销。相反，你刚刚撤销的操作会被作为重做（redo）
记录添加到撤销环中。这意味着当你再次执行撤销操作是，实际上会撤销（即重做）你刚刚执行的操作，
直到回到你上提停止时的状态为止；然后 Emacs 才会继续撤销缓冲区的其余更改。

*** Elemental Movement

**** Movement Asymmetry
移动的不对称性

Emacs will cleverly skip symbols and punctuation it encounters in the direction
(forward or backward) you're moving.

emacs 会在其移动方向上忽略首先遇到的标点符号。

**** Moving by S-Expressions
sexpr covers a wide range of commands that operate on balanced expressions
涵盖了对平衡表达式进行操作的多种命令。

通常包括以下内容：
字符串， 以`"` , `'`开始或结尾
括号，包含`[] {} () <>`
平衡表达式能跨越多行
其修饰键为`C-M-`
`C-M-f` 按s表达式向前移动
`C-M-b` 按s表达式向后移动

Down an Up List
`C-M-d` move down into a list
`C-M-u` move up out of a list
like the word commands, the list commands are not symmetric
going up will take you one level but leave your point at the opening character.
向上操作会提升一个层级，但将光标位置留在列表的起始字符处。

`C-M-u` 与 `C-M-k` (kill-sexp) 结合，用来删除刚刚所在位置的平衡表达式。

Forward and Backward List
`C-M-n` Move forward to next list
`C-M-p` Move backward to the previous list
The move to the next or the previos list expression in the same nested level.

通过 与`C-M-u` 组合， 在上级列表中移动。

Moving by Defun
`C-M-a` Move to begining of defun
`C-M-e` Move to end of defun

**** Scrolling
`C-v` Scroll down a near full screen
`M-v` Scrool up a near full screen
`C-M-v` Scroll down the other window
`C-M-S-v` Scroll up othe other window

`C-M-- C-M-v` Scroll up other other window either
`C-M--` means negative argument like `C-u`

*** Selections and Regions

Mark ring
`C-u C-@` return mark point
`C-x C-x` exchange-point-and-mark
`C-x SPC` rectangle-mark-mode

Setting the Mark
`M-h` Marks the next paragraph
`C-x h` Marks the whole buffer
`C-M-h` Marks the next defun
`M-@` Marks the next word
`C-M-<SPC>` `C-M-@` Marks the next s-expresion, usefull `C-M- C-M-<SPC>`
All mark commands append to the existing selection if you already have a
region active.
If you want to mark two words in a row, all you have to do is press `M-@` twice
or combine it with a numberic argument: `M-2 M-@`

*** Isearch: Incremental Search
`C-s`  Begins an incremental search
`C-r` Begins a backward incremental search
`C-M-s` Begins a regexp incremental search
`C-M-r` Begins a regexp backward incremental
must custom `isearch-allow-motion` to toggle open
`M-<, M->` Jump to first or last match
`C-v, M-v` Jump to the next or previos match not current visible
you can type `C-s C-s` to first open Isearch and then recall the last search string.

`M-n` Move to next item in search history
`M-p` Move to previos item in search history

`C-w` Add word ap point to search string. appendable
`C-M-y` Add character at point to search string. For unicode
`M-s C-e` Add rest of line at point to search string.
`C-y` Yank from clipboard to search string.

search toggle control
`M-s c` Toggle case-sensitivity
`M-s r` Toggle regular-expression mode
`M-s w` Toggle word mode. search can contain like `-` but no need to type
for `foo->bar = 42` can type `foo bar` search by `M-s w`
`M-s _` Toggle symbol mode
`M-s <SPC> Toggle lax whitespace matching
`M-s '` Toggle character folding

global key mapping for isearch
`M-s w` Isearch forward word
`M-s _` Isearch forward for symbol
`M-s .` Isearch forward for symbol at point
`M-s M-.` Isearch forward for thing at point

*** Occur
Print and Edit lines matching an expression
`M-s o` type `Meta and s and o` Occur mode (Outside Isearch)
`M-s o` Activate occur on current search string (Inside Isearch)
Unlike Isearch , you're asked for a regular expression for which to search.
Occur mode searches for lines that match the regular expression and shows you
the results in a sparate buffer.
use `line-matching-lines-default-context-lines` show context lines
Occur mode key binding
`M-n, M-p` Go to next and previous occurrence
`<,>` Go to beginningand end of buffer
`g` Revert the buffer, refreshing the search results
`q` Quits occur mode
`e` Switches to occur edit mode
`C-c C-c` Exits occur edit mode and applies changes

In origal windows
`M-g M-n` Jump to next "errro"
`M-g M-p" Jump to previos "error"
Can be used in `M-x compile` or `M-x grep` and support repeat mode

**** Multi-Occur
`M-x multi-occur-in-matching-buffers`  use `\.py$`
or use `M-x multi-occur` by select

*** Imenu

`M-g i` imenu can rebind in `M-i`

search uncertain comand by use `C-h a` apropos-command

** The Theory of Editing
*** Killing and Yanking Text
`C-d, DEL` Delete character
`<backspace> Delete previos character
`M-d, C-<backspace>` Kill word
`C-k` Kill rest of line
`M-k` Kill sentence
`C-M-k` Kill s-expression
`C-S-<backspace>` Kill current line

kill and yanking command
`C-w` Kill active region
`M-w` Copy to kill ring
`C-M-w` Append kill
`C-y` Yank last kill
`M-y` Cycle through kill ring
`M-y` show kill ring. This feature is only avaliable if
you haven't just called yank with `C-y`.

like undo ring, the Movement command broke the cycle.

*** Transposing Text
`C-t` Transpose characters
`M-t` Transpose words
`C-M-t` Transpose s-expression
`C-x C-t` Transpose lines

How Transposing Actually Works
The `M-t` command is intrinsically linked to the
`M-x forward-word (M-f)` command. Emacs will call `M-f` two times:
once with a negative argument, to get the left-side word to transpose;
and once again without a negative arguent, to get right-side word to
transpose

*** Search and Replace

`C-M-%` Query regexp search and replace
`M-%` Query search and replace
`M-x replace-string` Search and replace
`M-x replace-regexp` Regexp search and replace
You can also access Emacs's search adn replace from inside Isearch:
`C-M-%` Query regexp search and replace
`M-%` Query search and replace


** 工具观
为什么放弃了编写代码到极致的neovim 选择了emacs
首先是收到了tsoding的影响， 只用emacs基本裸配置， 通过compile 模式进行编译和
运行终端命令的方式完成代码的编写，调试。 然后看到油管视频【怒喷c++2小时】  认识到
c++ 可能真的适合持续投资， 内部有太多的边角情况，在真正写价值的代码之前， 会被
类的设置， 资源释放， 异常处理等占据时间， 从而还没深入到核心就放弃了。

然后从工具核心来说， emacs 是 all-in-one 的模式， 什么都在上面做， 而vim是
do one thing best 模式， 过去推崇后者， 让每个做到极致的软件相互配合。
这种思想是好，直到打开电脑后 不再打开终端，开启vim的时候，再好的软件，不去用也就无意义
而emacs可以写文档 org-mode， 文件管理 dired， 看视频 mpv 待加入工作流。随时地记录，
是怕遗忘， 怕一件事反复的在开头重复，浪费了时间， 不能真正深入。
到这一步，所谓代码补全， lsp协议反而是最不重要的了， emacs可以真正让你写起来， 至于
效率问题 emacs也有补全方案lsp， 而不是磨好了利剑，一直放在剑鞘中。

写东西要言之有物， 只说感悟只能让人心向往之而无实际作用现在持续总结emacs工作流，
不同于vim的模态编辑， emacs上该怎么做
目前我只有emacs的内置功能， 等到有需求了再去使用插件， 在此之前我想要找出emacs到底
该怎么用， 而不是把习惯往emacs上套。如果想了解有哪些好用的内置模式， 可以在 awesome-emacs
中去搜索`built-in`.

*** 工作流
代码中跳转 通过 `C-s` `C-r` 搜索， 可以Isearch 模式通过`M-s .`把光标下的单词加到
搜索框。 标记一个单词 使用`M-@`  标记一个表达式用`C-M-@` 这些指令都是累加的
TODO 是否做到repeat-mode 中？ 复制一行， 先删除一个再撤销， tsoding也是这样做。
`M-h` 标记一个段落， 这对写代码提出了要求， 按照功能分组便于复制。

compile 编译模式 输入编译命令后 如果错误，可以在当前窗口通过 `M-g M-n/p` 直接跳转
另外跟tsoding学的， 编译模式用来执行命令，比方代码执行 或者查询 `rg --vimgrep`

emacs  还有个优点是可以控制在不转移当前窗口的焦点的前提下操作另外的窗口
`C-M-v` `C-M-V` 控制其他窗口的上下翻页 `C-x 4 C-o` 在另外窗口切换buffer， `C-x 4 C-f`
在另外窗口打开文件 更多操作通过 `C-x 4 C-h h` 查看。

使用  tramp + qemu   让我在mac上可以使用到完整的linux开发，调试。也不用费劲心思想在mac上
装linux， 下载软件也很简单， 只需要 rg qmeu emacs-mac uv rust 再加上现在看从顶向下的 wireshark 
